#!/usr/bin/env node
// ponytail: ABIs come from the compiled artifacts, so the frontend can never
// drift from the contracts. Run after scripts/compile.mjs.
import fs from "node:fs";
import path from "node:path";

const OUT = path.join(process.cwd(), "out");
const TARGET = path.join(process.cwd(), "src", "lib", "abis.generated.ts");

const EXPORTS = [
  ["PUMP_ROBIN_FACTORY_ABI", "PumpRobinFactory"],
  ["BONDING_CURVE_ABI", "BondingCurve"],
  ["PUMP_ROBIN_TOKEN_ABI", "PumpRobinToken"],
  ["PUMP_ROBIN_HOOK_ABI", "PumpRobinHook"],
  ["PUMP_ROBIN_FEE_SHARE_ABI", "PumpRobinFeeShare"],
  ["PUMP_ROBIN_DEPLOYER_ABI", "PumpRobinDeployer"],
];

const parts = [
  "// GENERATED by scripts/gen-abis.mjs — do not edit by hand.",
  "// Source of truth: contracts/*.sol compiled into out/*.json.",
  "",
];

for (const [name, contract] of EXPORTS) {
  const file = path.join(OUT, `${contract}.json`);
  if (!fs.existsSync(file)) {
    console.error(`missing artifact: ${file} — run scripts/compile.mjs first`);
    process.exit(1);
  }
  const { abi } = JSON.parse(fs.readFileSync(file, "utf8"));
  parts.push(`export const ${name} = ${JSON.stringify(abi, null, 2)} as const;`);
  parts.push("");
  console.log(`${name.padEnd(28)} ${abi.length} entries`);
}

fs.mkdirSync(path.dirname(TARGET), { recursive: true });
fs.writeFileSync(TARGET, parts.join("\n"));
console.log(`\nwrote ${path.relative(process.cwd(), TARGET)}`);
